chservices:
  - type: web
    name: toolsfusion
    env: python
    buildCommand: 
      apt-get update && apt-get install -y zbar-tools && pip install -r requirements.txt
    startCommand: gunicorn TFProject.wsgi:application --bind
    ...
