services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: 
      apt-get update && apt-get install -y zbar-tools && pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    ...
