# Generated by Django 5.1.3 on 2025-01-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word2pdf', '0002_fileconversionp2d'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileConversion',
            new_name='FileConversionD2P',
        ),
    ]
