# Generated by Django 5.1.3 on 2025-01-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodetool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(help_text='Data encoded in the barcode', max_length=255)),
                ('barcode_type', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('code39', 'Code 39'), ('code128', 'Code 128'), ('itf', 'ITF'), ('isbn10', 'ISBN-10'), ('isbn13', 'ISBN-13')], default='code128', help_text='Type of the barcode (e.g., Code 128)', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Generated barcode image', null=True, upload_to='barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BRC',
        ),
    ]
