# Generated by Django 5.1.3 on 2025-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodetool', '0002_barcode_delete_brc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_type',
            field=models.CharField(choices=[('aztec', 'AZTEC'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('upce', 'UPC-E'), ('code39', 'Code 39'), ('code93', 'Code 93'), ('code128', 'Code 128'), ('itf', 'ITF'), ('isbn10', 'ISBN-10'), ('isbn13', 'ISBN-13'), ('issn', 'ISSN'), ('msi', 'MSI'), ('pharmacode', 'Pharmacode'), ('codabar', 'Codabar'), ('data_matrix', 'Data Matrix')], default='code128', help_text='Type of the barcode (e.g., Code 128)', max_length=20),
        ),
    ]
